#pragma once

#include <Liberty.inl>

enum D3DXBSTENCILOP
{
    D3DXBSTENCILOP_KEEP = 0,
    D3DXBSTENCILOP_ZERO = 1,
    D3DXBSTENCILOP_REPLACE = 2,
    D3DXBSTENCILOP_INCRSAT = 3,
    D3DXBSTENCILOP_DECRSAT = 4,
    D3DXBSTENCILOP_INVERT = 5,
    D3DXBSTENCILOP_INCR = 6,
    D3DXBSTENCILOP_DECR = 7
};
