[main]
file_path = "../private/default.xex"
out_directory_path = "../ppc"
switch_table_file_path = "./switch_table.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x826de8e0
savegprlr_14_address = 0x826de890
restfpr_14_address = 0x826dfb9c
savefpr_14_address = 0x826dfb50
restvmx_14_address = 0x826e1038
savevmx_14_address = 0x826e0da0
restvmx_64_address = 0x826e10cc
savevmx_64_address = 0x826e0e34

longjmp_address = 0x826e4f10
setjmp_address = 0x826e5030

functions = [
    { address = 0x8264C7C8, size = 0x68 },
    { address = 0x82636918, size = 0xD0 },
    { address = 0x8273C438, size = 0x4D8 },
    { address = 0x824A6180, size = 0x90 },
    { address = 0x82A97608, size = 0x64 },
    { address = 0x82775010, size = 0xD4 },
    { address = 0x8259A648, size = 0x84 },
    { address = 0x8273C110, size = 0x11C },
    { address = 0x821677D0, size = 0x7C },
    { address = 0x825B3A28, size = 0x84 },
    { address = 0x8273C368, size = 0xD0 },
    { address = 0x82912600, size = 0x11C },
    { address = 0x8244B920, size = 0x54 },
    { address = 0x82912A18, size = 0x254 },
    { address = 0x824C45B8, size = 0x50 },
    { address = 0x823D49A8, size = 0x1BC },
    { address = 0x8250F448, size = 0x98 },
    { address = 0x82763E28, size = 0x228 },
    { address = 0x828BFB18, size = 0x48 },
    { address = 0x82A97670, size = 0x5C },
    { address = 0x8223DF00, size = 0x144 },
    { address = 0x828B9CC8, size = 0x80 },
    { address = 0x8298D248, size = 0x100 },
    { address = 0x82218068, size = 0xA4 },
    { address = 0x8293F238, size = 0x114 },
    { address = 0x824C4550, size = 0x68 },
    { address = 0x82610860, size = 0x7C },
    { address = 0x821FDC28, size = 0x90 },
    { address = 0x82914568, size = 0x78 },
    { address = 0x8223EFE8, size = 0x14C },
    { address = 0x826103F0, size = 0x7C },
    { address = 0x82A975A0, size = 0x68 },
    { address = 0x8253B760, size = 0xEC },
    { address = 0x82833088, size = 0xB8 },
    { address = 0x82A976D0, size = 0x198 },
    { address = 0x829124F8, size = 0x100 },
    { address = 0x828A06B0, size = 0x114 },
    { address = 0x828C4B00, size = 0x1E4 },
    { address = 0x82333F80, size = 0xE8 },
    { address = 0x823D4768, size = 0x23C },
    { address = 0x821EE1C8, size = 0x5C },
    { address = 0x821EEAA8, size = 0xFC },
    { address = 0x825B4110, size = 0x5C },
    { address = 0x824C4498, size = 0xB4 },
    { address = 0x82217FC0, size = 0xA8 },
    { address = 0x827D9040, size = 0x380 },
    { address = 0x82A4B870, size = 0x78 },
    { address = 0x82A97868, size = 0x16C },
    { address = 0x82912728, size = 0x128 },
    { address = 0x82655978, size = 0x26C },
    { address = 0x82547890, size = 0x234 },
    { address = 0x8273C9B8, size = 0x364 },
    { address = 0x8223F138, size = 0xCC },
    { address = 0x82860FD0, size = 0x1A8 },
    { address = 0x829DA628, size = 0x70 },
    { address = 0x8223DD38, size = 0x1C4 },
    { address = 0x824ABA68, size = 0xE0 },
    { address = 0x824ABB10, size = 0x38 }
]

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
    { data = 0x826E3E60, size = 8 }, # C++ Frame Handler
    { data = 0x82AEA1CC, size = 8 } # C Specific Frame Handler
    # { data = 0x00485645, size = 44 } # End of .text
]

[[midasm_hook]]
name = "SetMSAALevel"
address = 0x82607CD4
registers = ["r4"]

[[midasm_hook]]
name = "RestoreTitleButtons"
address = 0x82512810
registers = ["r4"]
after_instruction = true

[[midasm_hook]]
name = "RestoreTitleButtons2"
address = 0x82512874
registers = ["r11"]
after_instruction = true

[[midasm_hook]]
name = "DisableTitleTaskStartWait"
address = 0x82512748
jump_address_on_true = 0x8251274C

[[midasm_hook]]
name = "SetDefaultTitleTaskSelection"
address = 0x82512B10
registers = ["r3", "r4"]

[[midasm_hook]]
name = "RenderCsdCastNodeMidAsmHook"
address = 0x828C8FBC
registers = ["r10", "r24"]

[[midasm_hook]]
name = "RenderCsdCastMidAsmHook"
address = 0x828C8FFC
registers = ["r4"]

[[midasm_hook]]
name = "ContextualHUD_LIFE_BER_ANIME_1"
address = 0x824D8044
registers = ["r5", "r31"]

[[midasm_hook]]
name = "ContextualHUD_LIFE_BER_ANIME_1"
address = 0x824D80A0
registers = ["r5", "r31"]

[[midasm_hook]]
name = "ContextualHUD_LIFE_BER_ANIME_1"
address = 0x824D8F2C
registers = ["r5", "r31"]

[[midasm_hook]]
name = "ContextualHUD_RING_1"
address = 0x824DEB38
registers = ["r5", "r31"]

[[midasm_hook]]
name = "PostureDisableEdgeGrabLeftover"
address = 0x82200568
registers = ["r31"]

[[midasm_hook]]
name = "PedestrianAnimationLOD"
address = 0x824C2808
registers = ["r29"]
after_instruction = true

[[midasm_hook]]
name = "MidairMachSpeedControl1"
address = 0x82210380
jump_address_on_true = 0x82210388

[[midasm_hook]]
name = "MidairMachSpeedControl2"
address = 0x822103B4
jump_address_on_true = 0x822103BC

[[midasm_hook]]
name = "MidairSnowboardControl1"
address = 0x82214710
jump_address_on_true = 0x82214714

[[midasm_hook]]
name = "MidairSnowboardControl2"
address = 0x82214878
jump_address_on_true = 0x8221487C

[[midasm_hook]]
name = "MidairSnowboardControl3"
address = 0x822145B8
jump_address_on_true = 0x822145BC

[[midasm_hook]]
name = "DisableHints"
address = 0x82487AC4
jump_address_on_true = 0x82487AC8

[[midasm_hook]]
name = "GetRenderWorldFBO"
address = 0x8260D6EC
registers = ["r4"]

[[midasm_hook]]
name = "FurtherObjectShadows"
address = 0x8260D7E0
registers = ["r26"]

[[midasm_hook]]
name = "DisableRadialBlur"
address = 0x82653834
jump_address_on_true = 0x82653840

[[midasm_hook]]
name = "PostureControlRotationSpeedFix"
address = 0x82201C6C
registers = ["f1", "r1"]

[[midasm_hook]]
name = "CriCueUpdateDeltaTimeFix"
address = 0x8260F238
registers = ["f13"]

[[midasm_hook]]
name = "PowerUpJingleDurationFix"
address = 0x8216CC28
registers = ["f31"]
