#pragma once

#include <Marathon.inl>

namespace Sonicteam::Player::State
{
    enum SonicState
    {
        SonicState_Wait = 0,
        SonicState_Walk = 1,
        SonicState_Run = 2,
        SonicState_Fall = 3,
        SonicState_Jump = 4,
        SonicState_CommonJump = 5,
        SonicState_Brake = 6,
        SonicState_QuickTurn = 7,
        SonicState_Dead = 8,
        SonicState_Damage = 9,
        SonicState_Push = 0xA,
        SonicState_Damage2 = 0xB,
        SonicState_Grind = 0xC,
        SonicState_Edge = 0xD,
        SonicState_EdgeTemplateCommonFall = 0xE,
        SonicState_EdgeTemplateCommonJump = 0xF,
        SonicState_Ottotto = 0x10,
        SonicState_SpringTemplateTypeA = 0x11,
        SonicState_WideSpring = 0x12,
        SonicState_SpringTemplateTypeB = 0x13,
        SonicState_DashPanel = 0x14,
        SonicState_SpringTemplateTypeC = 0x15,
        SonicState_Goal = 0x16,
        SonicState_Invincible = 0x17,
        SonicState_Wind = 0x18,
        SonicState_Landing = 0x19,
        SonicState_DontMove = 0x1A,
        SonicState_HoldObjectTemplate_571000 = 0x1B,
        SonicState_HoldObjectTemplate_622000 = 0x1E,
        SonicState_ChainJump = 0x1F,
        SonicState_RainbowRing = 0x20,
        SonicState_WallLanding = 0x21,
        SonicState_OnPathColli = 0x22,
        SonicState_BlastJump = 0x24,
        SonicState_Talk = 0x25,
        SonicState_PsiCatched = 0x26,
        SonicState_CommonSpringTemplate752000000 = 0x27,
        SonicState_Stun = 0x28,
        SonicState_Rodeo = 0x29,
        SonicState_Balancer = 0x2A,
        SonicState_WaterSlider = 0x2B,
        SonicState_Amigo = 0x30,
        SonicState_AmigoChase = 0x31,
        SonicState_GemThrow = 0x2E,
        SonicState_GemSnipe = 0x2F,
        SonicState_HomingSmash = 0x41,
        SonicState_Homing = 0x42,
        SonicState_HomingAfter = 0x43,
        SonicState_Sliding = 0x44,
        SonicState_Attack = 0x45,
        SonicState_SpinDash = 0x46,
        SonicState_Bound = 0x47,
        SonicState_LightDash = 0x48,
        SonicState_MachSpeed = 0x49,
        SonicState_TornadoGround = 0x4A,
        SonicState_TornadoAir = 0x4B,
        SonicState_SonicSuper = 0x4D
    };
}
